### ISSUE TITLE
@Autowired是否考虑增加List/Set/Map的注入呢？

### ISSUE THREAD

**Issue by hexian** [zzzzbw/doodle#1]
最近在写一个json转换工具，需要一个ioc容器，然后就搜到您这个项目了，我改造了下，使它能支持List/Set/Map的注入，您这边是否后续会考虑增加集合类型的注入呢？

**Comment by zzzzbw** [comment]
你说的这个注入是指Controller方法中的参数注入吧。
对于这种细节方面可能不会做很大的修改了，因为细节来说改来改去就无穷尽了。
不过欢迎你来提pr

**Comment by hexian** [comment]
好的， 我加入了一个List的注入
